import Header from "@/components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./Provider/Providers";
import SearchBox from "@/components/SearchBox/SearchBox";
// import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDB | Clone",
  description: "IMDB Clone Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          {/* <NavBar/> */}
          <SearchBox />
          <main className="container mx-auto"> {children}</main>
        </Providers>
      </body>
    </html>
  );
}
